"""empty message

Revision ID: 45c9449643b4
Revises: 74b79f63a863
Create Date: 2025-03-18 14:10:05.082732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c9449643b4'
down_revision: Union[str, None] = '74b79f63a863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_unique_constraint(None, 'cart', ['user_id'])
    op.add_column('cart_item', sa.Column('product_it', sa.Integer(), nullable=False))
    op.alter_column('cart_item', 'quantity',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('cart_item_product_fkey', 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'product', ['product_it'], ['id'])
    op.drop_column('cart_item', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.create_foreign_key('cart_item_product_fkey', 'cart_item', 'product', ['product'], ['id'])
    op.alter_column('cart_item', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    op.drop_column('cart_item', 'product_it')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    # ### end Alembic commands ###
