"""empty message

Revision ID: a331a6160ba6
Revises: b2b75db0835b
Create Date: 2025-02-20 21:32:31.004864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a331a6160ba6'
down_revision: Union[str, None] = 'b2b75db0835b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courier_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('courier', sa.Integer(), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=1, scale=6), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['userprofile.id'], ),
    sa.ForeignKeyConstraint(['courier'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_combo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combo_name', sa.String(length=32), nullable=False),
    sa.Column('combo_image', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combo_name')
    )
    op.create_index(op.f('ix_product_combo_id'), 'product_combo', ['id'], unique=False)
    op.create_table('store_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('store', sa.Integer(), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=1, scale=6), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client'], ['userprofile.id'], ),
    sa.ForeignKeyConstraint(['store'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    op.drop_table('store_review')
    op.drop_index(op.f('ix_product_combo_id'), table_name='product_combo')
    op.drop_table('product_combo')
    op.drop_table('courier_review')
    op.drop_table('cart')
    # ### end Alembic commands ###
